version: "3"
services:
  backend:
    image: ahmedgeek/xm-backend:latest
    environment:
      SERVICE_NAME: fpm
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - app-network

  client:
    image: ahmedgeek/xm-frontend:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: on-failure:3
networks:
  app-network:
    driver: bridge
